import type { PortfolioCategory, Testimonial } from './types';

export const portfolioData: PortfolioCategory[] = [
  {
    id: 'cv-lettres-motivation',
    title: 'CV & Lettres de motivation percutants',
    description: 'Plus de 50 modèles de CV et lettres de motivation modernes et professionnels pour vous démarquer auprès des recruteurs.',
  heroImage: 'img/CV professionnel.png',
    models: [
      // CV images (ids 101 - 141)
      { id: 101, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 001H.png', alt: 'Modèle de CV 001H' },
      { id: 102, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 002F.png', alt: 'Modèle de CV 002F' },
      { id: 103, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 003H.png', alt: 'Modèle de CV 003H' },
      { id: 104, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 004H.png', alt: 'Modèle de CV 004H' },
      { id: 105, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 005M.png', alt: 'Modèle de CV 005M' },
      { id: 106, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 006H.png', alt: 'Modèle de CV 006H' },
      { id: 107, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 007F.png', alt: 'Modèle de CV 007F' },
      { id: 108, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 008F.png', alt: 'Modèle de CV 008F' },
      { id: 109, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 009F.png', alt: 'Modèle de CV 009F' },
      { id: 110, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 010F.png', alt: 'Modèle de CV 010F' },
      { id: 111, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 011H.png', alt: 'Modèle de CV 011H' },
      { id: 112, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 012H.png', alt: 'Modèle de CV 012H' },
      { id: 113, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 013F.png', alt: 'Modèle de CV 013F' },
      { id: 114, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 014H.png', alt: 'Modèle de CV 014H' },
      { id: 115, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 015F.png', alt: 'Modèle de CV 015F' },
      { id: 116, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 016M.png', alt: 'Modèle de CV 016M' },
      { id: 117, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 017F.png', alt: 'Modèle de CV 017F' },
      { id: 118, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 018H.png', alt: 'Modèle de CV 018H' },
      { id: 119, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 019M.png', alt: 'Modèle de CV 019M' },
      { id: 120, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 020F.png', alt: 'Modèle de CV 020F' },
      { id: 121, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 021F.png', alt: 'Modèle de CV 021F' },
      { id: 122, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 022F.png', alt: 'Modèle de CV 022F' },
      { id: 123, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 023H.png', alt: 'Modèle de CV 023H' },
      { id: 124, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 024H.png', alt: 'Modèle de CV 024H' },
      { id: 125, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 025F.png', alt: 'Modèle de CV 025F' },
      { id: 126, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 026F.png', alt: 'Modèle de CV 026F' },
      { id: 127, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 027F.png', alt: 'Modèle de CV 027F' },
      { id: 128, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 028H.png', alt: 'Modèle de CV 028H' },
      { id: 129, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 029H.png', alt: 'Modèle de CV 029H' },
      { id: 130, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 030F.png', alt: 'Modèle de CV 030F' },
      { id: 131, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 031F.png', alt: 'Modèle de CV 031F' },
      { id: 132, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 032H.png', alt: 'Modèle de CV 032H' },
      { id: 133, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 033H.png', alt: 'Modèle de CV 033H' },
      { id: 134, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 034F.png', alt: 'Modèle de CV 034F' },
      { id: 135, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 035H.png', alt: 'Modèle de CV 035H' },
      { id: 136, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 036H.png', alt: 'Modèle de CV 036H' },
      { id: 137, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 037F.png', alt: 'Modèle de CV 037F' },
      { id: 138, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 038H.png', alt: 'Modèle de CV 038H' },
      { id: 139, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 039F.png', alt: 'Modèle de CV 039F' },
      { id: 140, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 040F.png', alt: 'Modèle de CV 040F' },
      { id: 141, imageSrc: 'img/CV & Lettres de motivation percutants/CV/CV 041F.png', alt: 'Modèle de CV 041F' },

      // Lettres de motivation (LM) images (ids 142 - 184)
      { id: 142, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 001.png', alt: 'Modèle de LM 001' },
      { id: 143, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 002.png', alt: 'Modèle de LM 002' },
      { id: 144, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 003.png', alt: 'Modèle de LM 003' },
      { id: 145, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 004.png', alt: 'Modèle de LM 004' },
      { id: 146, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 005.png', alt: 'Modèle de LM 005' },
      { id: 147, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 006.png', alt: 'Modèle de LM 006' },
      { id: 148, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 007.png', alt: 'Modèle de LM 007' },
      { id: 149, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 008.png', alt: 'Modèle de LM 008' },
      { id: 150, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 009.png', alt: 'Modèle de LM 009' },
      { id: 151, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 010.png', alt: 'Modèle de LM 010' },
      { id: 152, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 011.png', alt: 'Modèle de LM 011' },
      { id: 153, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 012.png', alt: 'Modèle de LM 012' },
      { id: 154, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 013.png', alt: 'Modèle de LM 013' },
      { id: 155, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 014.png', alt: 'Modèle de LM 014' },
      { id: 156, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 015.png', alt: 'Modèle de LM 015' },
      { id: 157, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 016.png', alt: 'Modèle de LM 016' },
      { id: 158, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 017.png', alt: 'Modèle de LM 017' },
      { id: 159, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 018.png', alt: 'Modèle de LM 018' },
      { id: 160, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 019.png', alt: 'Modèle de LM 019' },
      { id: 161, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 020.png', alt: 'Modèle de LM 020' },
      { id: 162, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 021.png', alt: 'Modèle de LM 021' },
      { id: 163, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 022.png', alt: 'Modèle de LM 022' },
      { id: 164, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 023.png', alt: 'Modèle de LM 023' },
      { id: 165, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 024.png', alt: 'Modèle de LM 024' },
      { id: 166, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 025.png', alt: 'Modèle de LM 025' },
      { id: 167, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 026.png', alt: 'Modèle de LM 026' },
      { id: 168, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 027.png', alt: 'Modèle de LM 027' },
      { id: 169, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 028.png', alt: 'Modèle de LM 028' },
      { id: 170, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 029.png', alt: 'Modèle de LM 029' },
      { id: 171, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 030.png', alt: 'Modèle de LM 030' },
      { id: 172, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 031.png', alt: 'Modèle de LM 031' },
      { id: 173, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 032.png', alt: 'Modèle de LM 032' },
      { id: 174, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 033.png', alt: 'Modèle de LM 033' },
      { id: 175, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 034.png', alt: 'Modèle de LM 034' },
      { id: 176, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 035.png', alt: 'Modèle de LM 035' },
      { id: 177, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 036.png', alt: 'Modèle de LM 036' },
      { id: 178, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 037.png', alt: 'Modèle de LM 037' },
      { id: 179, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 038.png', alt: 'Modèle de LM 038' },
      { id: 180, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 039.png', alt: 'Modèle de LM 039' },
      { id: 181, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 040.png', alt: 'Modèle de LM 040' },
      { id: 182, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 041.png', alt: 'Modèle de LM 041' },
      { id: 183, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 042.png', alt: 'Modèle de LM 042' },
      { id: 184, imageSrc: 'img/CV & Lettres de motivation percutants/LM/LM 043.png', alt: 'Modèle de LM 043' },
    ]
  },
  {
    id: 'portfolios-en-ligne',
    title: 'Portfolios en ligne modernes',
    description: 'Présentez vos travaux et compétences avec un site web élégant et responsive.',
    heroImage: 'img/Portfolio en ligne.png',
    models: [
      { id: 201, imageSrc: "img/Portfolios en ligne modernes/Neomorphic Developer Portfolio 01/Capture d'écran 2025-09-16 181732.png", alt: 'Neomorphic Developer Portfolio 01' },
      { id: 202, imageSrc: "img/Portfolios en ligne modernes/Glassmorphism UIUX Portfolio 02/Capture d'écran 2025-09-16 184455.png", alt: 'Glassmorphism UIUX Portfolio 02' },
      { id: 203, imageSrc: "img/Portfolios en ligne modernes/Cinematic Photographer Portfolio 03/Capture d'écran 2025-09-16 185752.png", alt: 'Cinematic Photographer Portfolio 03' },
      { id: 204, imageSrc: "img/Portfolios en ligne modernes/Architecte - Minimalisme Brutaliste Portfolio 04/Capture d'écran 2025-09-16 190811.png", alt: 'Architecte - Minimalisme Brutaliste Portfolio 04' },
      { id: 205, imageSrc: "img/Portfolios en ligne modernes/Artiste Digital - Psychédélique Fluide 05/Capture d'écran 2025-09-16 193024.png", alt: 'Artiste Digital - Psychédélique Fluide 05' },
      { id: 206, imageSrc: "img/Portfolios en ligne modernes/FuturaMetrics Dashboard 06/Capture d'écran 2025-09-16 193312.png", alt: 'FuturaMetrics Dashboard 06' },
      { id: 207, imageSrc: "img/Portfolios en ligne modernes/Chef Cuisinier 07/Capture d'écran 2025-09-16 193920.png", alt: 'Chef Cuisinier 07' },
      { id: 208, imageSrc: "img/Portfolios en ligne modernes/Consultant Tech - OS Portfolio 08/Capture d'écran 2025-09-16 205237.png", alt: 'Consultant Tech - OS Portfolio 08' },
      { id: 209, imageSrc: "img/Portfolios en ligne modernes/Atelier Noir 09/Capture d'écran 2025-09-16 195735.png", alt: 'Atelier Noir 09' },
      { id: 210, imageSrc: "img/Portfolios en ligne modernes/AR-Style 3DVFX Portfolio 10/Capture d'écran 2025-09-16 202708.png", alt: 'AR-Style 3DVFX Portfolio 10' },
    ]
  },
  {
    id: 'visuels-communication',
    title: 'Visuels (flyers, affiches, bannières)',
    description: 'Des créations graphiques impactantes pour vos campagnes de communication.',
    heroImage: 'img/Flyers-affiches.png',
    models: [
        { id: 301, imageSrc: 'img/Visuels (flyers, affiches, bannières)/001.png', alt: 'Modèle de Flyer 1' },
        { id: 302, imageSrc: 'img/Visuels (flyers, affiches, bannières)/002.png', alt: 'Modèle de Affiche 2' },
        { id: 303, imageSrc: 'img/Visuels (flyers, affiches, bannières)/003.jpg', alt: 'Modèle de Bannière 3' },
        { id: 304, imageSrc: 'img/Visuels (flyers, affiches, bannières)/004.jpg', alt: 'Modèle de Flyer 4' },
        { id: 305, imageSrc: 'img/Visuels (flyers, affiches, bannières)/005.jpg', alt: 'Modèle de Affiche 5' },
        { id: 306, imageSrc: 'img/Visuels (flyers, affiches, bannières)/006.jpg', alt: 'Modèle de Bannière 6' },
        { id: 307, imageSrc: 'img/Visuels (flyers, affiches, bannières)/007.jpg', alt: 'Modèle de Flyer 7' },
        { id: 308, imageSrc: 'img/Visuels (flyers, affiches, bannières)/008.jpg', alt: 'Modèle de Affiche 8' },
    ]
  },
  {
    id: 'logos-identite-visuelle',
    title: 'Création de logos & identité visuelle',
    description: 'Une identité forte et mémorable pour construire votre image de marque.',
    heroImage: 'img/Logo.png',
    models: [
        { id: 401, imageSrc: 'img/Création de logos & identité visuelle/001.jpg', alt: 'Modèle de Logo 1' },
        { id: 402, imageSrc: 'img/Création de logos & identité visuelle/002.jpg', alt: 'Modèle de Logo 2' },
        { id: 403, imageSrc: 'img/Création de logos & identité visuelle/003.png', alt: 'Modèle de Logo 3' },
        { id: 404, imageSrc: 'img/Création de logos & identité visuelle/004.png', alt: 'Modèle de Logo 4' },
        { id: 405, imageSrc: 'img/Création de logos & identité visuelle/005.png', alt: 'Modèle de Logo 5' },
        { id: 406, imageSrc: 'img/Création de logos & identité visuelle/006.png', alt: 'Modèle de Logo 6' },
        { id: 407, imageSrc: 'img/Création de logos & identité visuelle/007.png', alt: 'Modèle de Logo 7' },
        { id: 408, imageSrc: 'img/Création de logos & identité visuelle/008.png', alt: 'Modèle de Logo 8' },
        { id: 409, imageSrc: 'img/Création de logos & identité visuelle/009.png', alt: 'Modèle de Logo 9' },
    ]
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    quote: 'Leur approche professionnelle et créative a transformé mon CV. J\'ai obtenu plus d\'entretiens en une semaine qu\'en trois mois !',
    author: 'Julien Mercier',
    role: 'Développeur Full-Stack'
  },
  {
    id: 2,
    quote: 'Soutien Digital a créé une identité visuelle pour ma startup qui est à la fois moderne et parfaitement alignée avec nos valeurs. Le résultat est exceptionnel.',
    author: 'Carla Dubois',
    role: 'CEO & Fondatrice de Techova'
  },
  {
    id: 3,
    quote: 'Mon portfolio en ligne est magnifique et très fonctionnel. C\'est un outil indispensable qui met vraiment en valeur mon travail de photographe.',
    author: 'David Lemoine',
    role: 'Photographe Indépendant'
  }
];
